version: "3.9"

services:
  app:
    build: .
    container_name: app
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "7000:7000"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: freddybot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"


networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  postgres_data:
