- name: start
  type: command
  text: "<b>👋 Olá, {firstName}!</b>\n\n🤖 Eu estou aqui para automatizar as descrições das suas postagens no Canal!\n\n✨ Com o sistema de <b>Legendas Inteligentes</b>, suas publicações sempre terão descrições personalizadas e organizadas.\n\n📖 Consulte a aba  Como Usar para aprender a configurar tudo rapidamente!"
  buttons:
    - - text: "📋 Meus Dados"
        callback_data: "profile-info"
      - text: "🆘 Como Usar"
        callback_data: "help"
    - - text: "ℹ️ Sobre"
        callback_data: "about"

- name: profile-info
  type: callback
  text: |
    <b>📊 Informações da Conta</b>
    
    👤 <b>Usuário:</b> {firstName}
    🆔 <b>ID:</b> <code>{userId}</code>
    📆 <b>Registrado em:</b> {register}
    
    📡 <b>Canais Vinculados:</b> {countChannel}
    
    ⚙️ Gerencie suas configurações e acompanhe os canais vinculados pelo menu abaixo!"
  buttons:
    - - text: "👑 Assinatura VIP"
        callback_data: "subscribe-premium"
    - - text: "📝 Meus Canais"
        callback_data: "profile-user-channels"
      - text: "🏠 Início"
        callback_data: "start"
    - - text: "🔒 Assumir Controle"
        switch_inline_query_current_chat: "Claim "

- name: help
  text: "<b>🆘 Guia Rápido para Configuração</b>\n\n💡 Ativar as <b>Legendas Automáticas</b> no seu canal é simples:\n\n1️⃣ <b>Adicione o bot</b> {botUsername} ao seu canal.\n2️⃣ Conceda as seguintes permissões:\n   ✔️ Editar mensagens\n   ✔️ Fixar mensagens\n   ✔️ Publicar postagens\n   ✔️ Convidar usuários via link\n\n<blockquote><b>📌 Após isso, o bot enviará uma confirmação para você, é só confimar e o bot será ativado e pré configurado automaticamente.</b></blockquote>\n\n<b>Caso não funcione, encaminhe qualquer mensagem do seu canal mencionando o nome do canal para ativá-lo manualmente.</b>"
  buttons:
    - - text: "🏠 Início"
        callback_data: "start"

- name: about
  text: "<b>ℹ️ Sobre o Bot</b>\n\n<blockquote>📌 <b>Versão:</b> <i>{botVersion}</i>\n⚙️ <b>Desenvolvido Por:</b> <i>{ownerUser}</i></blockquote>\n\n🚀 Este bot foi criado para facilitar a adição de <b>legendas automáticas</b> em postagens de canais, tornando a gestão de conteúdo mais eficiente e dinâmica.\n\n📢 Para aprender a configurar, consulte a aba <a href='tg://user?id={botId}'>Ajuda</a>!"
  buttons:
    - - text: "🏠 Início"
        callback_data: "start"
      - text: "❓ Ajuda"
        callback_data: "help"

- name: profile-user-channels
  text: "<b>🏷️ Canais Vinculados</b>\n\n<blockquote>📌 Estes são os canais onde o bot está configurado para adicionar legendas automaticamente às postagens.</blockquote>\n\n<b>🔄 Se o bot for removido de um canal, ele deixará de aplicar as legendas e será removido automaticamente.</b>"
  buttons:
    - - text: "⬅️ Voltar"
        callback_data: "profile-info"

- name: config-channel
  text: "<b>📢 Canal Selecionado</b>\n\n<blockquote>🔹 <b>Nome:</b> {title}\n🔹 <b>ID:</b> <code>{channelId}</code></blockquote>\n\n<b>⚙️ Aqui você pode gerenciar as configurações de legendas deste canal. Edite conforme necessário e salve as alterações.</b>"
  buttons:
    - - text: "⚙ Configure Agora"
        web_app: "{webAppUrl}"
    - - text: "✨ Sticker Separador"
        callback_data: "sptc"
    - - text: "🔑 Transferir Acesso"
        callback_data: "paccess-info"
    #- - text: "🔗 Agrupar Canais"
        #callback_data: "gc-info:{channelId}"
    - - text: "🗑️ Remover Canal"
        callback_data: "del"
    - - text: "🔙 Voltar"
        callback_data: "profile-user-channels"
      - text: "🏠 Início"
        callback_data: "start"

- name: del
  text: "<b>⚠️ Confirmar Remoção</b>\n\n<blockquote>Você tem certeza que deseja remover o canal <b>{title}</b>?\nIsso desativará as legendas automáticas para este canal.</blockquote>\n\n<b>Esta ação não pode ser desfeita.</b> Toque no botão abaixo para confirmar."
  buttons:
    - - text: "✅ Confirmar"
        callback_data: "confirm-del:{channelId}"
      - text: "❌ Cancelar"
        callback_data: "config:{channelId}"

- name: confirm-del
  text: "<b>✅ Canal Removido</b>\n\n<blockquote>O canal <b>{title}</b> foi removido com sucesso. As legendas automáticas não serão mais adicionadas a este canal.</blockquote>\n\n<b>Você pode adicioná-lo novamente a qualquer momento, se desejar.</b>"
  buttons:
    - - text: "🔙 Voltar"
        callback_data: "profile-user-channels"
      - text: "🏠 Início"
        callback_data: "start"

- name: toadd-exist-channel
  text: "<b><i>💁 <a href='tg://user?id={botId}'>Adicionar</a> • Este canal <b>({channelName})</b> já foi adicionado anteriormente</i></b>"
  buttons:
    - - text: "📝 Meus Canais"
        callback_data: "profile-user-channels"
      - text: "🏠 Início"
        callback_data: "start"

        
- name: toadd-require-message
  text: "<b>❔ Confirmação necessária, {firstName}</b>\n\n<b><i>Você realmente deseja vincular o seguinte canal ao bot?</i></b>\n\n<blockquote>📌 <b>Canal:</b> <i>{channelName}</i>\n🔗 <b>ID:</b> <code>{channelId}</code></blockquote>\n\n✅ Se sim, clique em <b>Confirmar</b> para prosseguir.\n❌ Caso contrário, clique em <b>Cancelar</b>.\n\n⚠️ <i>Após a confirmação, o bot começará a gerenciar as legendas automáticas neste canal.</i>"
  buttons:
    - - text: "✅ | Confirmar"
        callback_data: "add-yes:{sessionKey}"
      - text: "❌ | Cancelar"
        callback_data: "add-not:{sessionKey}"

- name: toadd-success-message
  text: "<b>🎉 Sucesso, <a href='tg://user?id={botId}'>{firstName}</a>!</b>\n\n<b><i>✅ Seu <a href='tg://user?id={botId}'>Canal</a> foi vinculado com sucesso ao bot!</i></b>\n\n🔥 Agora, todas as postagens serão acompanhadas automaticamente por legendas personalizadas.\n\n📌 Se precisar ajustar alguma configuração, consulte a aba <a href='tg://user?id={botId}'>Ajuda</a>!"
  buttons:
    - - text: "⚙️ Configure Agora"
        web_app: "{miniAppUrl}"
    - - text: "📢 Meu Canal"
        callback_data: "config:{channelId}"
      - text: "🏠 Início"
        callback_data: "start"

- name: toadd-cancel-message
  text: "❌ <b>Vinculação cancelada</b>\n\nVocê cancelou o processo de vinculação do canal.\n\n<blockquote>📌 Caso precise de ajuda, acesse a aba <b>🆘 Como Usar</b> para aprender a configurar corretamente.</blockquote>"
  buttons:
    - - text: "🆘 Como Usar"
        callback_data: "help"
    - - text: "📋 Meus Dados"
        callback_data: "profile-info"
      - text: "🏠 Início"
        callback_data: "start"

- name: toadd-notfound-permissions-message
  text: "⚠️ <b>Permissões Insuficientes</b>\n\n<blockquote>📌 O bot precisa de permissões específicas para funcionar corretamente no canal.</blockquote>\n\n<b>✅ Verifique se o bot tem as seguintes permissões:</b>\n  • Editar mensagens\n  • Excluir mensagens\n  • Postar mensagens\n  • Convidar via link\n\n<blockquote>ℹ️ Consulte a aba <b>📖 Como Usar</b> para ver o passo a passo de como vincular seu canal corretamente.</blockquote>"
  buttons:
    - - text: "🏠 Início"
        callback_data: "start"
      - text: "🆘 Como Usar"
        callback_data: "help"


- name: ask-separator-message
  text: "✨ <b>Sticker Separador</b>\n\n<blockquote>Vamos deixar o canal <b>{channelName}</b> mais organizado?</blockquote>\n\nAdicione um sticker separador entre as postagens e dê um charme especial ao seu conteúdo!"
  buttons:
    - - text: "🧩 Adicionar"
        callback_data: "sptc-config"
      - text: "🗑️ Excluir"
        callback_data: "spex"
    - - text: "🔙 Voltar"
        callback_data: "config:{channelId}"

- name: require-separator-message
  text: "✨ <b>Sticker Separador</b>\n\n<blockquote>📌 Você está configurando um separador para o canal:</blockquote>\n\n🏷️ <b>Nome:</b> {channelName}\n🆔 <b>ID:</b> {channelId}\n\n<blockquote>📎 Envie um sticker que será usado como separador entre as postagens deste canal.</blockquote>\n\n<b>⚠️ Apenas stickers estáticos são recomendados para melhor visualização.</b>\n\n<b>✨ Deixe suas postagens com um toque especial e bem organizadas!</b>"
  buttons:
    - - text: "🔙 Voltar"
        callback_data: "sptc"

- name: failed-save-separator
  text: "✨ <b>Sticker Separador</b>\n\n<blockquote>❌ Não foi possível configurar o separador.</blockquote>\n\n📎 Verifique se você enviou um sticker válido.  \n⚠️ Apenas stickers estáticos são recomendados para melhor visualização.\n\n<b>🔁 Tente novamente e deixe suas postagens ainda mais organizadas!</b>"
  buttons:
    - - text: "🔙 Voltar"
        callback_data: "config:{channelId}"

- name: success-save-separator
  text: "✅ <b>Separador salvo com sucesso!</b>\n\nO sticker foi definido como separador para o canal <b>{channelName}</b>. Agora suas postagens vão ficar muito mais organizadas e estilosas!"
  buttons:
    - - text: "🔙 Voltar"
        callback_data: "config:{channelId}"

- name: success-delete-separator
  text: "✅ <b>Sticker Separador Removido!</b>\n\nO sticker separador do canal <b>{channelName}</b> foi excluído com sucesso.\n\n📌 Agora as postagens do canal não terão mais o separador entre elas. Se quiser, você pode adicionar um novo a qualquer momento!"
  buttons:
    - - text: "🔙 Voltar"
        callback_data: "config:{channelId}"


- name: ask-paccess-message
  text: "<b>🔄 Transferência de Acesso</b>\n\n<blockquote>📌 Você pode transferir a posse deste canal para outro usuário. O novo proprietário poderá gerenciar todas as configurações normalmente.</blockquote>\n\n<b>⚠️ Atenção:</b>\n<i>- Apenas o usuário que cadastrou o canal pode transferi-lo.</i>\n<i>- O novo dono deve ter interagido com o bot anteriormente.</i>\n<i>- Após a transferência, você perderá o controle sobre as configurações do canal.</i>\n\n<b>✅ Para continuar, inicie o processo de transferência abaixo.</b>"
  buttons:
    - - text: "🔑 Transferir Acesso"
        callback_data: "transfer"
    - - text: "🔙 Voltar"
        callback_data: "config:{channelId}"

- name: require-paccess-message
  text: "<b>📩 Informe o ID do Usuário</b>\n\n<blockquote>📌 Você está prestes a transferir a posse do canal:</blockquote>\n\n🏷️ <b>Nome:</b> {channelName}\n🆔 <b>ID:</b> {channelId}\n👤 <b>Registrado por:</b> {ownerName} ({ownerId})\n\n<blockquote>✏️ Envie o ID do usuário para quem deseja transferir a posse.</blockquote>\n\n<b>⚠️ Certifique-se de que o usuário já interagiu com o bot antes.</b>\n\n<b>🔹 Aguarde a confirmação antes de concluir a transferência.</b>"
  buttons:
    - - text: "🔙 Voltar"
        callback_data: "config:{channelId}"

- name: success-old-paccess-message
  text: "<b>✅ Transferência Concluída</b>\n\n<blockquote>📌 A posse do canal foi transferida com sucesso para o novo usuário.</blockquote>\n\n🏷️ <b>Canal:</b> {channelName}\n🆔 <b>ID:</b> {channelId}\n\n👤 <b>Novo Dono:</b> {newOwnerName} ({newOwnerId})\n\n🚀 <b>Agora, o novo proprietário pode gerenciar as configurações do canal normalmente.</b>"
  buttons:
    - - text: "🔙 Voltar"
        callback_data: "profile-user-channels"
      - text: "🏠 Início"
        callback_data: "start"

- name: success-new-paccess-message
  text: "<b>✅ Sucesso!</b>\n\n<blockquote>Agora você é o novo administrador do canal <i>{channelName}</i> (ID: <code>{channelId}</code>)! Todos os controles e configurações do bot estão sob sua responsabilidade.</blockquote>\n\n<b>🔹 Lembre-se de ajustar as configurações de legenda conforme necessário!</b>"
  buttons:
    - - text: "⚙️ Configure Agora"
        web_app: "{miniAppUrl}"
    - - text: "📢 Meu Canal"
        callback_data: "config:{channelId}"
      - text: "🏠 Início"
        callback_data: "start"


- name: ask-gc-message
  text: "<b>📌 Agrupamento de Canais</b>\n\n<blockquote>🔗 Este comando permite que você agrupe seus canais, exibindo os botões dos outros canais no canal selecionado.</blockquote>\n\n🛠️ <b>Como funciona?</b>\n➜ Se você tiver dois ou mais canais, pode vinculá-los para que os botões/plaquinhas de um canal apareçam no canal selecionado.\n➜ Isso facilita a navegação entre seus canais e melhora a experiência dos seus seguidores.\n\n⚙️ <b>Deseja prosseguir com o agrupamento?</b>\n✔️ Toque em 'Confirmar' para continuar.\n❌ Toque em 'Cancelar' para desistir"
  buttons:
    - - text: "✔️ Confirmar"
        callback_data: "gc.yes"
      - text: "❌ Cancelar"
        callback_data: "config:{channelId}"


- name: claim-ownership-require-message
  text: "<b>🔑 Assumir Controle do Canal</b>\n<blockquote>📌 Canal: <i>{channelName}</i>\n🔗 ID do Canal: <code>{channelId}</code>\n👤 Cadastrado por: <i>{ownerName}\n             - ID: {ownerId})</i></blockquote>\n<b>🔹 Se você for o administrador principal deste canal e deseja assumir o controle, clique em 'Assumir Controle'. Após a confirmação, você será o único responsável pelas configurações do bot neste canal.</b>"
  buttons:
    - - text: "✅ Aceitar"
        callback_data: "accept.claim:{sessionKey}"
      - text: "❌ Cancelar"
        callback_data: "config:{channelId}"


- name: publi
  text: "<b>📣 Automatize suas postagens com estilo!</b>\n\nCom o <b>@{botUsername}</b>, você adiciona <i>legendas automáticas</i> em todas as publicações do seu canal — sem esforço e com muito mais organização.\n\n<blockquote>\n💬 <b>Personalize</b> sua legenda do jeito que quiser  \n🧩 <b>Adicione separadores</b> com stickers estilosos  \n⚙️ <b>Edite</b> tudo facilmente com apenas alguns toques\n</blockquote>\n\n<b>✨ Ideal para canais que buscam agilidade, praticidade e um visual mais charmoso.</b>\n\n<i>Chega de colar legenda manualmente — o bot faz isso por você!</i> 🚀"
  buttons:
    - - text: "🎯 Quero no meu Canal"
        url: "t.me/{botUsername}?start=start"



- name: notfound-message
  text: "❌ <b>Comando não reconhecido!</b>\n\n✨ Parece que você tentou fazer algo que nem eu entendi… Talvez um bug na Matrix? Ou só um toque de criatividade mesmo!\n\nSe estiver em dúvida, corre lá na aba <b>Ajuda</b> — prometo te guiar com carinho e sem bugs!"
  buttons:
    - - text: "🏠 Início"
        callback_data: "start"


- name: toadd-payment-require-message
  text: "ℹ️ Atenção, {firstName}!!\n\nVocê atingiu o limite de canais gratuitos cadastrados.\n\nPara continuar e cadastrar este canal, é necessário realizar o pagamento.\n\n👇 Use o botão abaixo para prosseguir."
  buttons:
    - - text: "⭐ Pagar {value} Stars"
        pay: true
    - - text: "🎟️ Usar cupom"
        callback_data: "coupon-enter:{sessionKey}"
    - - text: "❌ | Cancelar Pagamento"
        callback_data: "cancel-pay:{sessionKey}"

- name: coupon-required-message
  text: |
    <b>🎟️ Cupom de desconto, {firstName}</b>

    Se você tiver um cupom, envie o código agora neste chat.

    <i>Caso contrário, é só prosseguir com o pagamento normalmente.</i>